### PR TITLE
Fixed answer retrieval

### PR DESCRIPTION
**Pull request by MDikkii**
Answer can be longer / shorter than correct answer so we should not probably limited the retrieval of given answer to correct answer size (even +1) but to the answer length itself

### CODE REVIEW

**Review by koral-- — COMMENTED** [review]
It seems that indeed there will be no crash but also comparison result will be incorrect.

**Comment by MDikkii** [comment]
Can you elaborate on that? I can see that GetStringUTFRegion won't add \0 to my buffer array.

**Comment by koral--** [comment]
See documentation:
https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#GetStringUTFRegion
`GetStringUTFRegion` just extracts some portion of the Java String it does not null-terminate them.

**Comment by MDikkii** [comment]
Ok, then I've added termination manually in ef01cfc, is it working solution right now?

**Comment by koral--** [comment]
Yep, now it should work.

**Comment by koral--** [comment]
Drop me a line at least 24h before GDG event on you want to pick up your swags so could bring them.

**Pull request merged**
